### ISSUE TITLE
Support for cloud fetch

### ISSUE THREAD

**Issue by ssainz** [databricks/databricks-sql-go#10]
Hello ~
Is there a plan to release the [cloud fetch feature](https://databricks.com/blog/2021/08/11/how-we-achieved-high-bandwidth-connectivity-with-bi-tools.html) in this thrift client for go or the [thrift client for node](https://github.com/databricks/databricks-sql-node)?
Thanks!

**Comment by susodapop** [comment]
We will do that at some point but we do not have immediate timeline.
