### ISSUE TITLE
Reusing connections with different tokens

### ISSUE THREAD

**Issue by ezbercihk** [databricks/databricks-sql-go#127]
Hello,

We have a use case where we need to execute queries as the logged in user in our app. I was looking for a way to reuse a connection (pool?) by simply changing the token before executing a query instead of maintaining a number of connections dedicated per user. Is this at all possible?

**Comment by ezbercihk** [comment]
@andrefurlan-db thank you for your response!

While waiting, I went the other way and created connectors using `WithAccessToken` method with user's access token, and then do `sql.OpenDB(connector)` and keep track of the `*sql.DB` instance returned in a TTL cache with key being sha256 of the access token. I think it has the same effect as you described.

I was hoping to use a single connector and update its access token right before firing a query to leverage a pool of http connections across the board but I guess it is not possible.

**Comment by andrefurlan-db** [comment]
Yeah, the driver package does not expose a good way to change connector config on the fly. I thought about exposing a way to pass in a HTTP client, but because we deal with thrift, the http client has many customizations ...
