### ISSUE TITLE
support for decimal type 

### ISSUE THREAD

**Issue by wale-kobai** [databricks/databricks-sql-go#130]
When I ran the query below, the `TRY_CAST(5.678  AS DECIMAL(38,5)) ` returned as a string while `-4.1D` came back as float64.  Could this be a result of go not having a decimal type? 

```sql 
"select 'ABC' AS title, TRY_CAST(5.678  AS DECIMAL(38,5)) AS rate, -4.1D as negative, 1234567890 as amount, TRY_CAST('2021-01-01 12:34:56.789' AS TIMESTAMP) as date"
```

| Column Name | Value                             | Go Type   |
| ----------- | --------------------------------- | --------- |
| title       | ABC                               | string    |
| rate        | "5.68000"                         | string    |
| negative    | \-4.1                             | float64   |
| amount      | 12345678901234567890              | int32     |
| date        | 2021-01-01 12:34:56.789 +0000 UTC | time.Time |

**Comment by rcypher-databricks** [comment]
Yes, currently the Go driver returns decimals as strings because there is not a canonical decimal type.
If you have a scenarios where this is causing problems we would be happy to discuss alternatives with you.

**Comment by wale-kobai** [comment]
Thank you, we can close this for now as we are able to work around this.
