### ISSUE TITLE
API to get databricks query ID

### ISSUE THREAD

**Issue by agchang** [databricks/databricks-sql-go#133]
Apologies if I missed something, but is there currently an API to get the databricks query id from a SQL query? Specifically, the one that shows up on the "Query History" on the Databricks UI. If I enable logging as in the [docs](https://pkg.go.dev/github.com/databricks/databricks-sql-go#hdr-CorrelationId_and_ConnId), I can see it, but not sure how to programmatically access this.

**Comment by rcypher-databricks** [comment]
The driverctx package exposes a function to allow adding a hook to the Context object passed to QueryContext() or ExecContext() which will be called with the query ID.
```
type IdCallbackFunc func(string)
func NewContextWithQueryIdCallback(ctx context.Context, callback IdCallbackFunc) context.Context
```

**Comment by agchang** [comment]
Thanks for the pointer. Are we guaranteed that the callback runs after the `db.QueryContext` statement?

**Comment by rcypher-databricks** [comment]
I just double checked the package documentation at https://pkg.go.dev/github.com/databricks/databricks-sql-go
 There's a section called 'Programmatically Retrieving Connection and Query Id' that describes this.
If it's alright with you I will mark this as closed.
