### ISSUE TITLE
Connecting to specific catalog not working

### ISSUE THREAD

**Issue by gilsegment** [databricks/databricks-sql-go#139]
In the README there is this example 
db, err := sql.Open("databricks", "token:********@********.databricks.com:443/sql/1.0/endpoints/********")
And it also says the DNS format is:
`token:[your token]@[Workspace hostname]:[Port number][Endpoint HTTP Path]?param=value`

So I figured that if I want to add catalog like described here https://docs.databricks.com/integrations/jdbc-odbc-bi.html#default-catalog-and-schema
The URL should be 
token:[your token]@[Workspace hostname]:[Port number][Endpoint HTTP Path]?ConnCatalog=main 
However this doesn't seems to work:
```
Configuration ConnCatalog is not available.",....,"message":"databricks: failed to execute query: query SET `ConnCatalog` = `main`;"}
```

**Comment by gilsegment** [comment]
After I change `ConnCatalog` to `ConnCatalog` it seems to work

**Comment by gilsegment** [comment]
Ohh yea sorry, I just edited it

**Comment by rcypher-databricks** [comment]
I will update the readme in the next release.  Are you ok with closing this issue?

**Comment by gilsegment** [comment]
Closed :)
