### ISSUE TITLE
Connect: Expose option to set protocol

### ISSUE THREAD

**Issue by MovieStoreGuy** [databricks/databricks-sql-go#140]
## Context

The method `WithServerHostname` will configure the protocol used to `http` if the value provided is `localhost`, however, it can be possible to try connector a compliant databricks service via a local proxy that does the TLS termination.

## Diagram

service --> reverse proxy --> service

## Outcomes

I am open to either outcome of:
- New option that can parse a complete URL and apply the `WithProtocol`, `WithHostname`, `WithPort`, `WithHTTPPath` configuration values
- New option that allows forcing http connection via a new option `WithHTTPProtocol`

**Comment by rcypher-databricks** [comment]
Just to verify: you are not using a dsn to connect, you are using NewConnector().

**Comment by MovieStoreGuy** [comment]
Yes, sorry that is correct.

**Comment by rcypher-databricks** [comment]
Version 1.4.0 has been released and allows for including http or https protocol when using WithServerHostname
ex. WithServerHostname("http:my.server.name")

**Comment by rcypher-databricks** [comment]
Unless there are still problems with this we will close this issue.
