### ISSUE TITLE
BUG with reading table that contains copied map

### ISSUE THREAD

**Issue by gilsegment** [databricks/databricks-sql-go#147]
There is a bug when reading values from a table that contains a map. 
It is reproduced only on a table that was created from copied values. 

I will describe here the exact steps to reproduce. If you don't have `main` catalog just replace with an exiting catalog name
1. From Databricks console run:
```
CREATE TABLE IF NOT EXISTS main.default.tableWithMap (
  id STRING,
  myMap MAP < STRING, STRING> 
);

insert into main.default.tableWithMap values ("1" , map('name', 'alice2'));
insert into main.default.tableWithMap values ("2" , map('name', 'bob2'));
insert into main.default.tableWithMap values ("3" , map('name', 'jon2'));

CREATE OR REPLACE TABLE main.default.copyOf_tableWithMap AS (
   SELECT * FROM main.default.tableWithMap
);
```

Now run the code:
```
func iterateOverTable(db *sql.DB) {
	fmt.Printf("\n============ iterateOverTable ============\n")
	rows, err := db.Query("select * from main.default.copyOf_tableWithMap")
	if err != nil {
		panic(err)
	}
	defer rows.Close()
	ctr := 0
	for rows.Next() {
		var (
			column1 sql.NullString
			column2 sql.NullString
		)
		if err = rows.Scan(&column1, &column2); err != nil {
			panic(err)
		}
		fmt.Printf("\n============ row #%d ============\n", ctr)
		fmt.Printf("%v | %v \n", column1.String, column2.String)
		ctr++
	}
}
```

The result will be :
```
============ iterateOverTable ============

============ row #0 ============
1 | {"name":"alice2"} 

============ row #1 ============
2 | {"name":"alice2"} 

============ row #2 ============
3 | {"name":"alice2"} 

```

Note that the map value is always the same!! 
If you run it on the original table. There is no issue, and the results are returning as expected. But when running on the copied table (named `copyOf_tableWithMap`), the results of the map is the same for all records which is a bug.
When running those queries on the Databricks console, it returns the correct results for both queries.

**Comment by rcypher-databricks** [comment]
I will try to reproduce this and let you know as soon as I have any results.

**Comment by rcypher-databricks** [comment]
A fix for this has been merged into the main branch and will be in the next release.

**Comment by gilsegment** [comment]
@rcypher-databricks any other use cases related to that bug, aside from the scenario I described above, which are worth mentioning?

**Comment by rcypher-databricks** [comment]
1.4.0 has been released, which includes the fix.  The issue was specific maps, so can't really think of other use cases.

**Comment by gilsegment** [comment]
@rcypher-databricks Awesome, thanks for the update!
