### ISSUE TITLE
Lack of clarity which DB connector is used under the hood

### ISSUE THREAD

**Issue by gilsegment** [databricks/databricks-sql-go#181]
This is a request to add a bit more info in the README regarding the connector that is used under the hood. 

In the [docs]( https://docs.databricks.com/en/integrations/jdbc-odbc-bi.html ) it seems that Databricks supports both ODBC and JDBC drivers. 

What is being used with this client library to connect to Databricks warehouse JDBC/ODBC/Something else?

I am using [this](https://github.com/databricks/databricks-sql-go/blob/main/connector.go#L90) to initialize the connector:

```
// NewConnector creates a connection that can be used with `sql.OpenDB()`.
// This is an easier way to set up the DB instead of having to construct a DSN string.
func NewConnector(options ...connOption) (driver.Connector, error) {
	// config with default options
	cfg := config.WithDefaults()

```

**Comment by susodapop** [comment]
The ODBC, JDBC, Python, NodeJS, and Go connectors all connect to Databricks via thrift.

**Comment by rcypher-databricks** [comment]
The Go driver is independent of JDBC/ODBC
