### ISSUE TITLE
Azure managed identities authentication support

### ISSUE THREAD

**Issue by shelldandy** [databricks/databricks-sql-go#231]
Do we have any sort of timeline on when this feature would be integrated to the driver?

https://learn.microsoft.com/en-us/azure/databricks/dev-tools/auth/#--supported-authentication-types-by-azure-databricks-tool-or-sdk

<img width="723" alt="image" src="https://github.com/databricks/databricks-sql-go/assets/7088511/27df5bdb-fd0c-4e68-9c58-c8428de7e933">

**Comment by shelldandy** [comment]
And if not is there any workaround to getting a client to connect maybe using the go-sdk?

**Comment by kravets-levko** [comment]
Hi @shelldandy! Unfortunately, this type of auth is currently not supported, and there are no estimates for implementing it. You can try to implement it yourself as a custom auth provider, and then use it with `dbsql.WithAuthenticator(authenticator)`:

https://github.com/databricks/databricks-sql-go/blob/d70ab7c5b6dda71f1439bd3edc51a2d2022f7d92/examples/oauth/main.go#L35-L39

**Comment by shelldandy** [comment]
@kravets-levko got this one working but had to do a small change of code, please see this PR:

https://github.com/databricks/databricks-sql-go/pull/244
