### ISSUE TITLE
Query execution weird behaviour

### ISSUE THREAD

**Issue by wale-kobai** [databricks/databricks-sql-go#58]
Hello, 

I'm experiencing a weird issue when running queries. I ran some delete queries and I checked the DB, and it behaved as expected. However, when I go into Azure, I see that the query is still running, and changes to complete, and after a long period, it times out due to inactivity,  then the status is revised as Failed.

The interesting thing is that the query does not roll back.

![1](https://user-images.githubusercontent.com/101576553/204536863-fd75bc4d-eb2d-4b93-9ed4-c81fa25e817f.png)
![2](https://user-images.githubusercontent.com/101576553/204536964-df3e4f96-775c-450c-875e-958aaf5eb09e.png)
![3](https://user-images.githubusercontent.com/101576553/204536976-c0c4bd17-6098-4a7d-af6b-dfa191972d35.png)
![4](https://user-images.githubusercontent.com/101576553/204536987-30c743d4-e2b8-4e90-96e9-0cad0b254cba.png)

We've previously tried the ODBC driver and did not experience this issue. 

Thank you

**Comment by andrefurlan-db** [comment]
Hi @wale-kobai , thanks for filing this. Just to confirm a few things, can you post an example of how you're using the driver? Are you closing the connection / result set? Inactivity errors are mostly due to an open execution that has not been closed for more than 10 minutes.

**Comment by andrefurlan-db** [comment]
@wale-kobai , I see. I'll try to reproduce your problem, meanwhile, can you `defer db.Close()`?

**Comment by wale-kobai** [comment]
The func NewSql is called from the main method. We can add the defer after `db := sql.OpenDB(connector)`. Or would you want us to open a connection per method call and close the connection after ?

**Comment by ezbercihk** [comment]
Hi @andrefurlan-db, we updated the code as follows to make sure we close the connection that *now* we get from the db instance after every execution. We are still seeing the same behavior.

```go
func (beSQL *BackendSQL) RunExec(query string) error {
	//utils.LogInfoMsg("[SQLExec] " + query)

	ctxRoot := dbsqlctx.NewContextWithCorrelationId(context.Background(), "Kobai RunExec")

	defer func() {
		if err := recover(); err != nil {
			fmt.Println("RunExec Panicked: ", err)
		}
	}()

        var err error
	var conn *sql.Conn
	if beSQL.Cfg.Top.Backend == "databricks" {
		conn, err = beSQL.Db.Conn(ctxRoot)
		if err == nil {
			defer conn.Close()
			_, err = conn.ExecContext(ctxRoot, query)
		}
	} else {
		_, err = beSQL.Db.Exec(query)
	}
	if err != nil {
		utils.LogError(err, "SQL Exec failed.")
		return err
	}

	return nil
}
```

**Comment by andrefurlan-db** [comment]
Hi @wale-kobai and @ezbercihk! Sorry for the confusion. I just mean:
```go
// ...
db := sql.OpenDB(connector)
defer db.Close()
// ...
```
The sql package will take care of the connection pool, so no need to close per connection. It is just good to make sure the pool gets drained at the end of Main().

I was unable to reproduce (maybe different DBR versions), but I'll push a fix anyway that in theory should help.

**Comment by andrefurlan-db** [comment]
Hi @wale-kobai. @ezbercihk. We found the root cause. We addressed what we could here: https://github.com/databricks/databricks-sql-go/pull/65

The problem was that a query that returns rows was issued using ExecContext, and ExecContext was not preemptively closing the result set. Databricks will at first consider the query successful and wait until the client fetch all results. In this case, the client did not fetch, and then after 10 minutes or so the query would be marked as inactive and failed.

This can still happen if you use QueryContext, get rows, and do not close it until fetching all results. So please be careful with this scenario.

Please test and let us know if it is now working as expected.

Thanks for the help.

**Comment by ezbercihk** [comment]
@andrefurlan-db thank you! We are running our tests and observing. We were not getting an end time for the queries in the Databricks UI but with this change we can see them populated now. We will update as we complete the end to end testing to make sure all is working as intended.

**Comment by ezbercihk** [comment]
@andrefurlan-db we finished testing. Everything is looking great! Thank you for turning this around quickly! We really appreciate it.
