### ISSUE TITLE
Thrift file missing

### ISSUE THREAD

**Issue by aminebizid** [databricks/databricks-sql-go#59]
Hello,
I'm trying to create a .net sql connector but the Thrift file is missing.
Could you provide it please

**Comment by andrefurlan-db** [comment]
Hi @aminebizid, we don't officially support .Net for Databricks thrift. Have you tried to use the open source version?
https://thrift.apache.org/lib/netstd.html

**Comment by aminebizid** [comment]
Hi @andrefurlan-db 
Thanks for your response
I'm using https://thrift.apache.org/lib/netstd.html but I just need the .thrift file you are using to generate the code

**Comment by andrefurlan-db** [comment]
closing this issue as we can't provide the file yet. Next year we'll probably work on a .Net connector for Databricks.
