### ISSUE TITLE
Query with named parameters

### ISSUE THREAD

**Issue by jennifer-yan** [databricks/databricks-sql-go#84]
I have a issue for query with named parameters when switching to version v0.2.2 from v0.1.4.

Previously, I was using the driver version v0.1.4, and make query with named parameters and it could work.
q:=select app_id from view_stream_prepared where org_id=@orgId limit 5;
orgId:="abc"
db.Query(q,sql.Named("orgId", orgId))

Now I am switching to the new driver version 0.2.2.
I always got the error "query parameters are not supported"
Can anyone give an example of query with named parameters for the newest release?

**Comment by andrefurlan-db** [comment]
Hi @jennifer-yan . Query params are not support in Databricks yet. We are planning to release the feature some time in the beginning of next year. The older version of the driver would simple reconstruct your query string, which is not safe. You are better qualified to construct the query and check if the params are safe then the driver.

Thanks for your question.

Andre

**Comment by jennifer-yan** [comment]
Thank you very much.

**Comment by jennifer-yan** [comment]
Hi @andrefurlan-db,
I have upgraded the driver to v1.0.1, but it still returns the error "query parameters are not supported". Can you confirm if query parameters is supported in v1.0.1. I can' t find it in recent release notes.

**Comment by andrefurlan-db** [comment]
Hi @jennifer-yan, unfortunately, query parameters are still not supported in Databricks. We'll add support for it in the driver as soon as we add support for it in Databricks.

The support will come first with Named Parameters:
https://github.com/apache/spark/pull/38712

Later we'll also support Positional Parameters, but work on that has not started.

**Comment by jennifer-yan** [comment]
Hi @andrefurlan-db , is there any estimated release time for this feature?

**Comment by hariso** [comment]
+1 from me as well! An open-source project I work on would benefit from this.

**Comment by cdecoux** [comment]
It looks like the parameterized queries were added in Spark 3.4.0: https://issues.apache.org/jira/browse/SPARK-41271 

I assume this is just a matter of when the Databricks SQL release channels push out Spark 3.4.0 support? Looks like they're currently at 3.3.2.

**Comment by Vizualni** [comment]
Can we reopen this issue? It's something that I've stumbled upon and having this feature would be super helpful.

**Comment by LLay** [comment]
+1 for this feature. It would enable my company to use sqlx Named queries to issue queries like `WHERE _ IN (:args)`

**Comment by echarrod** [comment]
Would also appreciate this feature. I was going to create a new issue but saw this one: is there a reason it's closed, when a fix hasn't been implemented?

**Comment by andrefurlan-db** [comment]
This has been implemented. Please check the example: https://github.com/databricks/databricks-sql-go/blob/main/examples/parameters/main.go
