### ISSUE TITLE
databricks: query parameters are not supported

### ISSUE THREAD

**Issue by JunyuanZhangCoin** [databricks/databricks-sql-go#96]
Hi team,
I updated the Golang databricks sql version from v0.1.4 to v1.0.1, and I started getting this error. Why is the support for query parameters removed? Will it be supported in the future?

**Comment by andrefurlan-db** [comment]
Please see: https://github.com/databricks/databricks-sql-go/issues/84

**Comment by andrefurlan-db** [comment]
Thanks for updating, though! A lot has improved and the driver is way more stable. I hope you find that explanation for dropping the client-side support for query parameters sufficient.

Andre

**Comment by JunyuanZhangCoin** [comment]
Thank you!
